/* eslint-disable no-console */
/**
 * SIAKAD demo seeder.
 *
 * Adds realistic Indonesian-school dummy data on top of the baseline
 * (`seed.ts`): puluhan berita, 24 item galeri, 12 mata pelajaran, 6 kelas,
 * 120 siswa, 18 guru, 5 ujian CBT siap dijalankan, 30 hari absensi, 6 PPDB
 * applicants, pengumuman, jadwal pelajaran, nilai, dan parent links.
 *
 * Pictures are loaded from /public/img (AI-generated by scripts/generate-images.py).
 * If a hero/gallery image is missing, the seeder falls back to a placeholder URL
 * so the demo is still usable without pre-generated assets.
 *
 * Run AFTER `tsx prisma/seed.ts`:
 *   tsx prisma/seed-demo.ts
 */
import fs from 'node:fs';
import path from 'node:path';

import argon2 from 'argon2';

import { prisma } from '../src/shared/db/prisma';
import { ROLES, type RoleCode } from '../src/modules/rbac/permissions';

const PROJECT_ROOT = path.resolve(__dirname, '..');
const HERO_DIR = path.join(PROJECT_ROOT, 'public', 'img', 'hero');
const GAL_DIR = path.join(PROJECT_ROOT, 'public', 'img', 'gallery');
const NEWS_DIR = path.join(PROJECT_ROOT, 'public', 'img', 'news');

function publicImage(rel: string, fallback: string): string {
  const abs = path.join(PROJECT_ROOT, 'public', rel.replace(/^\//, ''));
  return fs.existsSync(abs) ? `/${rel.replace(/^\//, '')}` : fallback;
}

function pickHero(): string {
  for (const name of ['hero-1.jpg', 'hero-2.jpg', 'hero-3.jpg']) {
    const abs = path.join(HERO_DIR, name);
    if (fs.existsSync(abs)) return `/img/hero/${name}`;
  }
  return 'https://placehold.co/1280x720/1d4ed8/ffffff?text=SIAKAD';
}

function pickGalleryImage(i: number): string {
  const name = `gallery-${String(((i - 1) % 24) + 1).padStart(2, '0')}.jpg`;
  const abs = path.join(GAL_DIR, name);
  if (fs.existsSync(abs)) return `/img/gallery/${name}`;
  return `https://placehold.co/1280x720/1d4ed8/ffffff?text=Galeri+${i}`;
}

function pickNewsImage(i: number): string {
  const newsName = `news-${String(((i - 1) % 12) + 1).padStart(2, '0')}.jpg`;
  const newsAbs = path.join(NEWS_DIR, newsName);
  if (fs.existsSync(newsAbs)) return `/img/news/${newsName}`;
  // Fallback to gallery image if news image not generated yet.
  return pickGalleryImage(i);
}

const NEWS_TITLES: Array<{ title: string; excerpt: string }> = [
  {
    title: 'Tim Olimpiade Matematika Raih Medali Emas Tingkat Nasional',
    excerpt:
      'Tiga siswa SMA Negeri Contoh berhasil membawa pulang medali emas pada Olimpiade Sains Nasional 2026.',
  },
  {
    title: 'Pelaksanaan Upacara Hari Pendidikan Nasional Berlangsung Khidmat',
    excerpt:
      'Seluruh warga sekolah mengikuti upacara peringatan Hardiknas dengan tema "Merdeka Belajar untuk Semua".',
  },
  {
    title: 'Workshop Robotika Kolaborasi dengan Universitas Terkemuka',
    excerpt:
      'Klub Robotika menggelar workshop intensif selama tiga hari bersama dosen tamu dari ITB.',
  },
  {
    title: 'Tim Futsal Sekolah Lolos Babak Final POPDA Provinsi',
    excerpt:
      'Setelah mengalahkan tiga tim seeded, tim futsal melaju ke final tingkat provinsi tahun ini.',
  },
  {
    title: 'Pameran Seni Rupa Tahunan: Karya Siswa Memukau Pengunjung',
    excerpt:
      'Pameran tahunan menampilkan 120 karya lukis, patung, dan instalasi karya siswa kelas X-XII.',
  },
  {
    title: 'Donor Darah PMR: 87 Pendonor Berpartisipasi',
    excerpt:
      'Kegiatan donor darah rutin yang diselenggarakan PMR berhasil menggalang 87 kantong darah.',
  },
  {
    title: 'Kunjungan Industri Siswa SMK ke Pabrik Otomotif',
    excerpt:
      'Siswa jurusan TKR melakukan kunjungan industri untuk memahami proses produksi langsung di lapangan.',
  },
  {
    title: 'Sosialisasi PPDB Online 2026/2027 Resmi Dibuka',
    excerpt:
      'Penerimaan Peserta Didik Baru tahun ajaran baru dibuka mulai 1 Mei sampai 30 Juni 2026.',
  },
  {
    title: 'Program Beasiswa Prestasi untuk 30 Siswa Terbaik',
    excerpt:
      'Yayasan dan komite sekolah meluncurkan program beasiswa untuk 30 siswa berprestasi akademik dan non-akademik.',
  },
  {
    title: 'Lomba Debat Bahasa Inggris: Tim Kami Juara Pertama Kabupaten',
    excerpt:
      'Tim debat bahasa Inggris SMA Negeri Contoh menjadi juara pertama lomba debat tingkat kabupaten.',
  },
  {
    title: 'Pelatihan Guru Penggerak: Implementasi Kurikulum Merdeka',
    excerpt:
      'Sebanyak 28 guru mengikuti pelatihan implementasi Kurikulum Merdeka selama dua minggu.',
  },
  {
    title: 'Festival Budaya Nusantara: Setiap Kelas Tampilkan Tarian Daerah',
    excerpt:
      'Festival budaya tahunan menampilkan tarian dari Sabang sampai Merauke yang dipersiapkan setiap kelas.',
  },
  {
    title: 'Implementasi Sistem CBT untuk Ujian Tengah Semester',
    excerpt:
      'Mulai semester ini, seluruh ujian tengah semester dilakukan secara digital dengan sistem CBT.',
  },
  {
    title: 'Bakti Sosial OSIS: Pembagian 200 Paket Sembako untuk Lansia',
    excerpt:
      'OSIS bersama pengurus RT/RW setempat membagikan 200 paket sembako kepada warga lansia kurang mampu.',
  },
  {
    title: 'Lomba Cipta Puisi Bahasa Indonesia: Karya Siswa Terbaik',
    excerpt:
      'Tiga karya puisi terbaik diumumkan pada acara peringatan Bulan Bahasa, dengan tema "Bahasa Pemersatu".',
  },
  {
    title: 'Klub Astronomi Adakan Pengamatan Gerhana Bulan Total',
    excerpt:
      'Klub astronomi mengadakan pengamatan gerhana bulan total bersama warga sekolah pada malam hari.',
  },
  {
    title: 'Program Adiwiyata: Sekolah Raih Predikat Mandiri',
    excerpt:
      'Setelah lima tahun konsisten dengan program lingkungan, sekolah memperoleh predikat Adiwiyata Mandiri.',
  },
  {
    title: 'Kegiatan Pesantren Kilat Ramadhan 1447 H',
    excerpt:
      'Kegiatan pesantren kilat dengan tema "Generasi Qurani" diikuti seluruh siswa muslim selama satu pekan.',
  },
  {
    title: 'Lomba Esai Sejarah Tingkat Kota: Juara II',
    excerpt:
      'Sariah Putri (XI IPS-2) meraih juara II lomba esai sejarah tingkat kota dengan judul "Jejak Diponegoro".',
  },
  {
    title: 'Hari Bumi: Tanam 500 Pohon di Lingkungan Sekolah',
    excerpt:
      'Memperingati Hari Bumi, seluruh warga sekolah menanam 500 pohon trembesi dan pucuk merah.',
  },
  {
    title: 'Klinik Kesehatan Sekolah: Pemeriksaan Berkala Siswa',
    excerpt:
      'UKS bekerja sama dengan Puskesmas mengadakan pemeriksaan kesehatan berkala untuk seluruh siswa kelas X.',
  },
  {
    title: 'Lomba Karya Tulis Ilmiah: Inovasi Energi Terbarukan',
    excerpt:
      'Tiga siswa IPA berhasil masuk 10 besar lomba KTI nasional dengan tema energi terbarukan.',
  },
  {
    title: 'Pertukaran Pelajar Internasional: 5 Siswa Berangkat ke Jepang',
    excerpt:
      'Lima siswa terpilih mengikuti program pertukaran pelajar selama dua minggu di Tokyo dan Kyoto.',
  },
  {
    title: 'Kampanye Anti Bullying: Ikrar Sekolah Ramah Anak',
    excerpt:
      'Seluruh siswa dan guru menandatangani ikrar sekolah ramah anak sebagai komitmen anti bullying.',
  },
  {
    title: 'Sosialisasi Bahaya Narkoba bersama BNN Provinsi',
    excerpt:
      'BNN Provinsi memberikan sosialisasi tentang bahaya narkoba kepada siswa kelas X dan XI.',
  },
  {
    title: 'Pelatihan Public Speaking untuk Pengurus OSIS',
    excerpt:
      'Pengurus OSIS dan MPK mengikuti pelatihan public speaking dengan trainer profesional.',
  },
  {
    title: 'Pekan Literasi: Tantangan Membaca 5 Buku dalam Sebulan',
    excerpt:
      'Perpustakaan menggelar tantangan membaca dengan hadiah menarik bagi peserta paling produktif.',
  },
  {
    title: 'Try Out UTBK SBMPTN: Persiapan Siswa Kelas XII',
    excerpt:
      'Try out UTBK SBMPTN diikuti 240 siswa kelas XII dengan simulasi sistem ujian sesungguhnya.',
  },
  {
    title: 'Bazaar Wirausaha Siswa: Produk Lokal Siswa Laku Keras',
    excerpt:
      'Bazaar wirausaha siswa dalam rangka kewirausahaan menghasilkan omzet lebih dari 25 juta rupiah.',
  },
  {
    title: 'Wisuda Purna Siswa Angkatan 2026: Selamat Berkarya',
    excerpt:
      'Sebanyak 312 siswa kelas XII secara resmi diwisuda dalam acara purna siswa angkatan ke-29.',
  },
];

const GALLERY_ITEMS: Array<{ category: string; title: string }> = [
  { category: 'Kegiatan Sekolah', title: 'Upacara Bendera Senin Pagi' },
  { category: 'Akademik', title: 'Praktikum di Laboratorium Komputer' },
  { category: 'Akademik', title: 'Eksperimen Kimia Kelas XII IPA-1' },
  { category: 'Olahraga', title: 'Pertandingan Sepak Bola Antar Kelas' },
  { category: 'Olahraga', title: 'Final Basket POPDA Provinsi' },
  { category: 'Seni & Budaya', title: 'Marching Band Tampil di HUT Sekolah' },
  { category: 'Seni & Budaya', title: 'Tari Saman Mewakili Sekolah' },
  { category: 'Seni & Budaya', title: 'Ensemble Angklung Tradisional' },
  { category: 'Seni & Budaya', title: 'Pameran Lukisan Siswa' },
  { category: 'Akademik', title: 'Kelas Tata Boga Memasak Bersama' },
  { category: 'Ekstrakurikuler', title: 'Klub Robotika Merakit Lengan Robot' },
  { category: 'Seni & Budaya', title: 'Paduan Suara Tampil di Panggung' },
  { category: 'Kegiatan Sekolah', title: 'Wisuda Purna Siswa Angkatan 2026' },
  { category: 'Akademik', title: 'Pameran Karya Tulis Ilmiah' },
  { category: 'Ekstrakurikuler', title: 'Pendakian Pramuka di Gunung Salak' },
  { category: 'Akademik', title: 'Membaca di Perpustakaan' },
  { category: 'Kegiatan Sekolah', title: 'Open House Sekolah' },
  { category: 'Olahraga', title: 'Hari Olahraga: Lari 100m Putri' },
  { category: 'Akademik', title: 'Ruang Ujian CBT Bersih dan Tertib' },
  { category: 'Kegiatan Sekolah', title: 'Field Trip ke Museum Nasional' },
  { category: 'Kegiatan Sekolah', title: 'Penanaman Pohon di Hari Bumi' },
  { category: 'Akademik', title: 'Lomba Debat Bahasa Inggris' },
  { category: 'Kegiatan Sekolah', title: 'Hari Batik: Memakai Batik Tradisional' },
  { category: 'Kegiatan Sekolah', title: 'MPLS Penyambutan Siswa Baru' },
];

const SUBJECTS = [
  { code: 'MTK', name: 'Matematika', kkm: 75 },
  { code: 'BIN', name: 'Bahasa Indonesia', kkm: 75 },
  { code: 'BIG', name: 'Bahasa Inggris', kkm: 75 },
  { code: 'FIS', name: 'Fisika', kkm: 70 },
  { code: 'KIM', name: 'Kimia', kkm: 70 },
  { code: 'BIO', name: 'Biologi', kkm: 70 },
  { code: 'SEJ', name: 'Sejarah Indonesia', kkm: 75 },
  { code: 'GEO', name: 'Geografi', kkm: 75 },
  { code: 'EKO', name: 'Ekonomi', kkm: 75 },
  { code: 'SOS', name: 'Sosiologi', kkm: 75 },
  { code: 'PJOK', name: 'Pendidikan Jasmani Olahraga & Kesehatan', kkm: 75 },
  { code: 'INF', name: 'Informatika', kkm: 75 },
];

const FIRST_NAMES_M = [
  'Adi',
  'Bagus',
  'Candra',
  'Dimas',
  'Eko',
  'Fajar',
  'Galih',
  'Hadi',
  'Iqbal',
  'Joko',
  'Krisna',
  'Lukman',
  'Made',
  'Nanda',
  'Oka',
  'Putra',
  'Raka',
  'Surya',
  'Teguh',
  'Wahyu',
];
const FIRST_NAMES_F = [
  'Anisa',
  'Bunga',
  'Cinta',
  'Dewi',
  'Erika',
  'Fatma',
  'Gina',
  'Hana',
  'Indah',
  'Jessica',
  'Kirana',
  'Larasati',
  'Mira',
  'Nabila',
  'Olivia',
  'Putri',
  'Rina',
  'Sinta',
  'Tasya',
  'Wulan',
];
const LAST_NAMES = [
  'Saputra',
  'Wijaya',
  'Pratama',
  'Sukma',
  'Lestari',
  'Anggraini',
  'Permata',
  'Hidayat',
  'Nugroho',
  'Hartono',
  'Santoso',
  'Kusumawardhani',
  'Maharani',
  'Purnama',
  'Surya',
  'Wibowo',
  'Hendra',
  'Putri',
  'Yulianti',
  'Pertiwi',
];

function pickName(seed: number): { fullName: string; gender: 'L' | 'P' } {
  const isMale = seed % 2 === 0;
  const first = isMale
    ? FIRST_NAMES_M[seed % FIRST_NAMES_M.length]!
    : FIRST_NAMES_F[seed % FIRST_NAMES_F.length]!;
  const last = LAST_NAMES[(seed * 7) % LAST_NAMES.length]!;
  return { fullName: `${first} ${last}`, gender: isMale ? 'L' : 'P' };
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)+/g, '');
}

async function ensureRoles(): Promise<Record<RoleCode, string>> {
  const roles = await prisma.role.findMany({ where: { code: { in: Object.values(ROLES) } } });
  const map = {} as Record<RoleCode, string>;
  for (const r of roles) {
    map[r.code as RoleCode] = r.id;
  }
  return map;
}

async function ensureAcademicYear(): Promise<{ id: string }> {
  return prisma.academicYear.upsert({
    where: { code: '2025/2026-Ganjil' },
    update: { isActive: true },
    create: {
      code: '2025/2026-Ganjil',
      startDate: new Date('2025-07-15'),
      endDate: new Date('2025-12-20'),
      isActive: true,
    },
  });
}

async function ensureSchoolProfile(): Promise<void> {
  const heroNote = pickHero();
  await prisma.schoolProfile.upsert({
    where: { id: 'default-school' },
    update: {
      logoUrl: '/icons/icon-192.png',
      website: 'https://sekolah-contoh.sch.id',
      visionText:
        'Mencetak generasi unggul, berkarakter Pancasila, berdaya saing global, dan peduli lingkungan.',
      missionText:
        'Menyelenggarakan pendidikan bermutu berbasis nilai luhur, mengembangkan potensi peserta didik secara holistik melalui Kurikulum Merdeka, serta menjalin kerja sama dengan dunia usaha dan industri (DUDI).',
    },
    create: {
      id: 'default-school',
      name: 'SMA Negeri Contoh',
      level: 'SMA',
      address: 'Jl. Pendidikan No. 1, Jakarta Selatan, DKI Jakarta 12190',
      phone: '+62-21-7220-0000',
      email: 'info@sekolah-contoh.sch.id',
      website: 'https://sekolah-contoh.sch.id',
      logoUrl: '/icons/icon-192.png',
      visionText:
        'Mencetak generasi unggul, berkarakter Pancasila, berdaya saing global, dan peduli lingkungan.',
      missionText:
        'Menyelenggarakan pendidikan bermutu berbasis nilai luhur, mengembangkan potensi peserta didik secara holistik melalui Kurikulum Merdeka, serta menjalin kerja sama dengan dunia usaha dan industri (DUDI).',
    },
  });
  // Best-effort: log which hero we resolved (for ops visibility).
  console.log(`  · school logo + visi/misi updated (hero hint: ${heroNote})`);
}

async function seedSubjects(): Promise<Map<string, string>> {
  const map = new Map<string, string>();
  for (const s of SUBJECTS) {
    const sub = await prisma.subject.upsert({
      where: { code: s.code },
      update: { name: s.name, kkm: s.kkm },
      create: s,
    });
    map.set(s.code, sub.id);
  }
  return map;
}

async function seedTeachers(roles: Record<RoleCode, string>): Promise<Array<{ id: string; fullName: string }>> {
  const teachers: Array<{ id: string; fullName: string }> = [];
  const password = await argon2.hash('Guru!2026', { type: argon2.argon2id });
  for (let i = 1; i <= 18; i++) {
    const { fullName } = pickName(i + 100);
    const username = `guru${String(i).padStart(2, '0')}`;
    const email = `${username}@sekolah-contoh.sch.id`;
    const nip = `1985${String(i).padStart(2, '0')}01200001`;
    const user = await prisma.user.upsert({
      where: { email },
      update: { isActive: true, fullName, nip },
      create: {
        email,
        username,
        passwordHash: password,
        fullName,
        nip,
        isActive: true,
        roles: { connect: [{ id: roles.guru! }] },
      },
    });
    teachers.push({ id: user.id, fullName });
  }
  // Designate first 6 as wali kelas as well
  const waliRole = roles.wali_kelas!;
  for (let i = 0; i < 6; i++) {
    await prisma.user.update({
      where: { id: teachers[i]!.id },
      data: { roles: { connect: [{ id: waliRole }] } },
    });
  }
  return teachers;
}

async function seedClasses(
  yearId: string,
  teachers: Array<{ id: string; fullName: string }>,
): Promise<Array<{ id: string; name: string; level: string }>> {
  const defs = [
    { name: 'X IPA-1', level: 'X' },
    { name: 'X IPS-1', level: 'X' },
    { name: 'XI IPA-1', level: 'XI' },
    { name: 'XI IPS-1', level: 'XI' },
    { name: 'XII IPA-1', level: 'XII' },
    { name: 'XII IPS-1', level: 'XII' },
  ];
  const out: Array<{ id: string; name: string; level: string }> = [];
  for (let i = 0; i < defs.length; i++) {
    const d = defs[i]!;
    const cls = await prisma.class.upsert({
      where: { academicYearId_name: { academicYearId: yearId, name: d.name } },
      update: { homeroomTeacherId: teachers[i]!.id, level: d.level },
      create: {
        academicYearId: yearId,
        name: d.name,
        level: d.level,
        homeroomTeacherId: teachers[i]!.id,
      },
    });
    out.push({ id: cls.id, name: cls.name, level: cls.level });
  }
  return out;
}

async function seedStudents(
  roles: Record<RoleCode, string>,
  classes: Array<{ id: string; name: string }>,
): Promise<Array<{ id: string; fullName: string; classId: string; classIndex: number }>> {
  const password = await argon2.hash('Siswa!2026', { type: argon2.argon2id });
  const out: Array<{ id: string; fullName: string; classId: string; classIndex: number }> = [];
  for (let i = 1; i <= 120; i++) {
    const classIndex = (i - 1) % classes.length;
    const cls = classes[classIndex]!;
    const { fullName } = pickName(i);
    const username = `siswa${String(i).padStart(3, '0')}`;
    const email = `${username}@siswa.sekolah-contoh.sch.id`;
    const nis = `2025${String(i).padStart(4, '0')}`;
    const user = await prisma.user.upsert({
      where: { email },
      update: { isActive: true, fullName, nis },
      create: {
        email,
        username,
        passwordHash: password,
        fullName,
        nis,
        isActive: true,
        roles: { connect: [{ id: roles.siswa! }] },
      },
    });
    await prisma.classEnrollment.upsert({
      where: { classId_studentId: { classId: cls.id, studentId: user.id } },
      update: {},
      create: { classId: cls.id, studentId: user.id },
    });
    out.push({ id: user.id, fullName, classId: cls.id, classIndex });
  }
  return out;
}

async function seedSchedules(
  classes: Array<{ id: string; name: string }>,
  subjects: Map<string, string>,
  teachers: Array<{ id: string }>,
): Promise<void> {
  const subjectCodes = [...subjects.keys()];
  const slots: Array<[number, string, string]> = [
    [1, '07:00', '08:30'],
    [1, '08:45', '10:15'],
    [1, '10:30', '12:00'],
    [2, '07:00', '08:30'],
    [2, '08:45', '10:15'],
    [3, '07:00', '08:30'],
    [3, '08:45', '10:15'],
    [4, '07:00', '08:30'],
    [5, '07:00', '08:30'],
  ];
  for (const cls of classes) {
    for (let s = 0; s < slots.length; s++) {
      const slot = slots[s]!;
      const subjId = subjects.get(subjectCodes[s % subjectCodes.length]!)!;
      const teacher = teachers[s % teachers.length]!;
      try {
        await prisma.classSchedule.upsert({
          where: {
            classId_dayOfWeek_startTime: {
              classId: cls.id,
              dayOfWeek: slot[0],
              startTime: slot[1],
            },
          },
          update: {},
          create: {
            classId: cls.id,
            subjectId: subjId,
            teacherId: teacher.id,
            dayOfWeek: slot[0],
            startTime: slot[1],
            endTime: slot[2],
            room: `R-${cls.name.replace(/\s+/g, '')}`,
          },
        });
      } catch {
        // Ignore unique-conflict racey upserts on dev DBs.
      }
    }
  }
}

async function seedAttendance(
  students: Array<{ id: string; fullName: string }>,
): Promise<void> {
  // 14 weekdays (avoid Sun=0 / Sat=6) up to today.
  const today = new Date();
  today.setHours(7, 0, 0, 0);
  const days: Date[] = [];
  for (let d = 0; d < 28 && days.length < 14; d++) {
    const date = new Date(today.getTime() - d * 24 * 60 * 60 * 1000);
    const dow = date.getDay();
    // Always include today (so the dashboard "hari ini" looks populated even on
    // weekends), then keep weekdays only for the rest of the history.
    if (d === 0 || (dow !== 0 && dow !== 6)) days.push(date);
  }
  const statuses = ['present', 'present', 'present', 'present', 'present', 'late', 'sick', 'permission', 'absent'];
  // Idempotent: clear existing demo attendance for these students within the
  // 14-day window so repeated `seed-demo` runs don't accumulate duplicates.
  const studentIds = students.map((s) => s.id);
  if (studentIds.length > 0 && days.length > 0) {
    const min = new Date(days[days.length - 1]!);
    min.setHours(0, 0, 0, 0);
    const max = new Date(days[0]!);
    max.setHours(23, 59, 59, 999);
    await prisma.attendanceMark.deleteMany({
      where: { studentId: { in: studentIds }, date: { gte: min, lte: max } },
    });
  }
  for (const stu of students) {
    for (const day of days) {
      // Deterministic pseudo-random by student+day.
      const seed = (stu.id.charCodeAt(0) + day.getDate()) % statuses.length;
      const status = statuses[seed]!;
      const notes =
        status === 'sick'
          ? 'Sakit demam'
          : status === 'permission'
            ? 'Izin keluarga'
            : status === 'late'
              ? 'Terlambat 10 menit'
              : status === 'absent'
                ? 'Tanpa keterangan'
                : null;
      try {
        await prisma.attendanceMark.create({
          data: {
            studentId: stu.id,
            date: day,
            status,
            notes: notes ?? undefined,
          },
        });
      } catch {
        // Skip if duplicate index (rare).
      }
    }
  }
}

async function seedExams(
  yearId: string,
  subjects: Map<string, string>,
  classes: Array<{ id: string; name: string }>,
): Promise<Array<{ id: string; title: string }>> {
  const defs = [
    { code: 'MTK', title: 'Penilaian Tengah Semester — Matematika' },
    { code: 'BIN', title: 'Penilaian Tengah Semester — Bahasa Indonesia' },
    { code: 'BIG', title: 'Penilaian Tengah Semester — Bahasa Inggris' },
    { code: 'FIS', title: 'Penilaian Akhir Semester — Fisika' },
    { code: 'INF', title: 'Penilaian Harian — Informatika' },
  ];
  const out: Array<{ id: string; title: string }> = [];
  const now = new Date();
  for (let i = 0; i < defs.length; i++) {
    const d = defs[i]!;
    const subjectId = subjects.get(d.code);
    if (!subjectId) continue;
    const startAt = new Date(now.getTime() - 30 * 60 * 1000);
    const endAt = new Date(now.getTime() + 24 * 60 * 60 * 1000);
    const exam = await prisma.exam.upsert({
      where: { id: `demo-exam-${i + 1}` },
      update: {
        title: d.title,
        startAt,
        endAt,
        durationMinutes: 60,
        isPublished: true,
      },
      create: {
        id: `demo-exam-${i + 1}`,
        academicYearId: yearId,
        subjectId,
        title: d.title,
        description:
          'Soal pilihan ganda, mode CBT dengan fullscreen lock, deteksi tab-switch, dan autosave jawaban.',
        startAt,
        endAt,
        durationMinutes: 60,
        shuffleQuestions: true,
        shuffleAnswers: true,
        isPublished: true,
        fullscreenRequired: true,
        preventTabSwitch: true,
        maxTabSwitches: 2,
      },
    });
    // Map ke semua kelas demo.
    for (const cls of classes) {
      await prisma.examClassMapping.upsert({
        where: { examId_classId: { examId: exam.id, classId: cls.id } },
        update: {},
        create: { examId: exam.id, classId: cls.id },
      });
    }
    // Soal contoh
    await seedQuestions(exam.id, d.code);
    out.push({ id: exam.id, title: exam.title });
  }
  return out;
}

const QUESTION_BANK: Record<string, Array<{ q: string; choices: string[]; correctIndex: number }>> = {
  MTK: [
    { q: 'Hasil dari 12 × 8 + 24 ÷ 6 adalah …', choices: ['96', '100', '104', '108'], correctIndex: 1 },
    {
      q: 'Diketahui f(x) = 2x² − 3x + 1. Nilai f(3) adalah …',
      choices: ['10', '12', '14', '16'],
      correctIndex: 0,
    },
    {
      q: 'Persamaan kuadrat dengan akar 2 dan −5 adalah …',
      choices: ['x² + 3x − 10 = 0', 'x² − 3x − 10 = 0', 'x² − 3x + 10 = 0', 'x² + 3x + 10 = 0'],
      correctIndex: 0,
    },
    {
      q: 'Turunan dari y = x³ + 4x² − x adalah …',
      choices: ['3x² + 8x − 1', '3x² + 4x − 1', '2x² + 8x', 'x² + 8x + 1'],
      correctIndex: 0,
    },
    {
      q: 'Nilai sin 30° + cos 60° adalah …',
      choices: ['½', '1', '√3', '√2'],
      correctIndex: 1,
    },
    {
      q: 'Banyak susunan huruf dari kata "BAGUS" adalah …',
      choices: ['60', '120', '720', '24'],
      correctIndex: 1,
    },
    {
      q: 'Jika ²log 8 = x, maka x = …',
      choices: ['2', '3', '4', '8'],
      correctIndex: 1,
    },
    {
      q: 'Jumlah deret aritmatika 5 + 8 + 11 + … (10 suku) adalah …',
      choices: ['170', '185', '195', '210'],
      correctIndex: 1,
    },
    {
      q: 'Volume kubus dengan rusuk 6 cm adalah …',
      choices: ['36 cm³', '108 cm³', '216 cm³', '324 cm³'],
      correctIndex: 2,
    },
    {
      q: 'Penyelesaian dari |2x − 4| < 6 adalah …',
      choices: ['−1 < x < 5', 'x < 5', 'x > −1', '−5 < x < 1'],
      correctIndex: 0,
    },
  ],
  BIN: [
    {
      q: 'Kalimat yang menggunakan ejaan baku adalah …',
      choices: [
        'Saya pergi ke apotik membeli obat.',
        'Saya pergi ke apotek membeli obat.',
        'Saya pergi ke apotek membeli obatnya.',
        'Saya pergi ke apotik membeli obat-obat.',
      ],
      correctIndex: 1,
    },
    {
      q: 'Sinonim kata "hemat" adalah …',
      choices: ['boros', 'cermat', 'sederhana', 'tidak'],
      correctIndex: 1,
    },
    {
      q: 'Majas yang membandingkan dua hal dengan kata "seperti" adalah majas …',
      choices: ['metafora', 'personifikasi', 'simile', 'hiperbola'],
      correctIndex: 2,
    },
    {
      q: '"Hujan deras mengguyur kota Jakarta tadi malam." Kalimat tersebut termasuk …',
      choices: ['kalimat tunggal', 'kalimat majemuk setara', 'kalimat majemuk bertingkat', 'kalimat aktif transitif'],
      correctIndex: 0,
    },
    {
      q: 'Unsur intrinsik cerpen yang menggambarkan tempat dan waktu adalah …',
      choices: ['tema', 'alur', 'latar', 'amanat'],
      correctIndex: 2,
    },
    {
      q: 'Kalimat efektif berikut yang benar adalah …',
      choices: [
        'Para hadirin sekalian dimohon untuk berdiri.',
        'Hadirin dimohon berdiri.',
        'Para hadirin yang dimohon berdiri.',
        'Para hadirin sekalian berdirilah.',
      ],
      correctIndex: 1,
    },
    {
      q: 'Penulisan kata depan yang tepat adalah …',
      choices: ['Disekolah', 'Di sekolah', 'Disekolahkan', 'Di-sekolah'],
      correctIndex: 1,
    },
    {
      q: 'Cerita rakyat dari Jawa Barat tentang asal-usul Tangkuban Perahu adalah …',
      choices: ['Malin Kundang', 'Sangkuriang', 'Bawang Merah Bawang Putih', 'Roro Jonggrang'],
      correctIndex: 1,
    },
  ],
  BIG: [
    {
      q: 'She _____ to school every day.',
      choices: ['go', 'goes', 'going', 'went'],
      correctIndex: 1,
    },
    {
      q: 'The opposite of "expensive" is …',
      choices: ['cheap', 'rich', 'big', 'difficult'],
      correctIndex: 0,
    },
    {
      q: 'Choose the correct passive form of: "They built the bridge in 1990."',
      choices: [
        'The bridge was built in 1990.',
        'The bridge has built in 1990.',
        'The bridge built in 1990.',
        'The bridge is built in 1990.',
      ],
      correctIndex: 0,
    },
    {
      q: 'I have lived here _____ ten years.',
      choices: ['since', 'for', 'during', 'while'],
      correctIndex: 1,
    },
    {
      q: 'Which sentence is grammatically correct?',
      choices: [
        'He don\'t like coffee.',
        'He doesn\'t like coffee.',
        'He isn\'t likes coffee.',
        'He not likes coffee.',
      ],
      correctIndex: 1,
    },
    {
      q: 'A person who writes books is called a …',
      choices: ['painter', 'singer', 'author', 'doctor'],
      correctIndex: 2,
    },
  ],
  FIS: [
    {
      q: 'Satuan SI untuk gaya adalah …',
      choices: ['joule', 'pascal', 'newton', 'watt'],
      correctIndex: 2,
    },
    {
      q: 'Sebuah benda bermassa 2 kg bergerak dengan kecepatan 4 m/s. Energi kinetiknya adalah …',
      choices: ['4 J', '8 J', '16 J', '32 J'],
      correctIndex: 2,
    },
    {
      q: 'Hukum I Newton dikenal dengan hukum …',
      choices: ['kelembaman', 'aksi-reaksi', 'gravitasi', 'kekekalan energi'],
      correctIndex: 0,
    },
    {
      q: 'Cahaya merupakan gelombang …',
      choices: ['mekanik', 'longitudinal', 'elektromagnetik', 'bunyi'],
      correctIndex: 2,
    },
    {
      q: 'Rumus tekanan adalah …',
      choices: ['P = F × A', 'P = F/A', 'P = m × g', 'P = ρgh × A'],
      correctIndex: 1,
    },
    {
      q: 'Dalam rangkaian listrik seri, yang sama nilainya untuk semua komponen adalah …',
      choices: ['tegangan', 'arus', 'hambatan', 'daya'],
      correctIndex: 1,
    },
  ],
  INF: [
    {
      q: 'Bahasa pemrograman yang umumnya berjalan pada peramban tanpa kompilasi tambahan adalah …',
      choices: ['C++', 'Java', 'JavaScript', 'COBOL'],
      correctIndex: 2,
    },
    {
      q: 'Struktur data LIFO (Last In First Out) disebut …',
      choices: ['queue', 'stack', 'tree', 'graph'],
      correctIndex: 1,
    },
    {
      q: 'Singkatan HTTP adalah …',
      choices: [
        'High Transfer Text Protocol',
        'HyperText Transfer Protocol',
        'Hyper Transmission Text Protocol',
        'Hot Text Transfer Protocol',
      ],
      correctIndex: 1,
    },
    {
      q: 'Database relasional menggunakan bahasa query …',
      choices: ['HTML', 'CSS', 'SQL', 'XML'],
      correctIndex: 2,
    },
    {
      q: 'Algoritma pengurutan yang membandingkan tetangga dan menukar bila salah urutan disebut …',
      choices: ['quick sort', 'merge sort', 'bubble sort', 'heap sort'],
      correctIndex: 2,
    },
    {
      q: 'Komponen perangkat keras yang berfungsi sebagai memori utama adalah …',
      choices: ['CPU', 'RAM', 'SSD', 'GPU'],
      correctIndex: 1,
    },
  ],
};

async function seedQuestions(examId: string, code: string): Promise<void> {
  const bank = QUESTION_BANK[code] ?? [];
  for (let i = 0; i < bank.length; i++) {
    const item = bank[i]!;
    // Pre-compute the deterministic question id we want (idempotent re-seeding).
    const qId = `${examId}-q${i + 1}`;
    const existing = await prisma.question.findUnique({ where: { id: qId } });
    if (existing) continue;
    await prisma.question.create({
      data: {
        id: qId,
        examId,
        type: 'mcq',
        prompt: item.q,
        order: i + 1,
        points: 1,
        choices: {
          create: item.choices.map((text, idx) => ({
            label: String.fromCharCode(65 + idx),
            text,
            isCorrect: idx === item.correctIndex,
            order: idx,
          })),
        },
      },
    });
  }
}

async function seedAnnouncements(): Promise<void> {
  const items = [
    {
      title: 'Libur Hari Raya: 10–14 April 2026',
      body: 'Diberitahukan kepada seluruh warga sekolah bahwa kegiatan belajar-mengajar diliburkan dalam rangka Hari Raya Idulfitri.',
      isPinned: true,
    },
    {
      title: 'Pengumpulan Buku Rapor Sisipan',
      body: 'Wali kelas wajib mengumpulkan buku rapor sisipan paling lambat Jumat, 20 Mei 2026 ke ruang TU.',
      isPinned: false,
    },
    {
      title: 'Latihan Upacara Hari Pendidikan Nasional',
      body: 'Latihan upacara akan dilaksanakan setiap hari pukul 14:00–16:00 di lapangan utama.',
      isPinned: false,
    },
    {
      title: 'Sosialisasi Beasiswa Kuliah',
      body: 'Akan dilaksanakan sosialisasi beasiswa Bidikmisi dan KIP Kuliah pada Sabtu, 15 Mei 2026 di aula.',
      isPinned: false,
    },
    {
      title: 'Pemilihan Ketua OSIS Periode 2026/2027',
      body: 'Pendaftaran calon ketua OSIS dibuka mulai 1–10 Juni 2026 di sekretariat OSIS.',
      isPinned: false,
    },
    {
      title: 'Jadwal Penilaian Akhir Semester',
      body: 'PAS dilaksanakan tanggal 1–10 Desember 2025 dengan sistem CBT. Pastikan kuota internet siap.',
      isPinned: true,
    },
  ];
  for (const it of items) {
    const existing = await prisma.announcement.findFirst({ where: { title: it.title } });
    if (existing) continue;
    await prisma.announcement.create({
      data: {
        title: it.title,
        body: it.body,
        audience: 'all',
        publishedAt: new Date(),
        isPinned: it.isPinned,
      },
    });
  }
}

async function seedNews(): Promise<void> {
  const now = Date.now();
  for (let i = 0; i < NEWS_TITLES.length; i++) {
    const item = NEWS_TITLES[i]!;
    const slug = `${slugify(item.title)}-${i + 1}`;
    const publishedAt = new Date(now - i * 36 * 60 * 60 * 1000); // every 1.5 days
    await prisma.newsPost.upsert({
      where: { slug },
      update: { isPublished: true, publishedAt, coverImageUrl: pickNewsImage(i + 1) },
      create: {
        slug,
        title: item.title,
        excerpt: item.excerpt,
        content: `<p>${item.excerpt}</p><p>Berita ini merupakan contoh konten dummy untuk SIAKAD. Konten lengkap akan ditulis oleh redaksi sekolah lewat panel CMS.</p><p>Liputan: tim humas SIAKAD. Foto: dokumentasi sekolah / AI generated.</p>`,
        coverImageUrl: pickNewsImage(i + 1),
        isPublished: true,
        publishedAt,
        seoTitle: item.title,
        seoDescription: item.excerpt,
      },
    });
  }
}

async function seedGallery(): Promise<void> {
  // Upsert categories.
  const catNames = Array.from(new Set(GALLERY_ITEMS.map((g) => g.category)));
  const cats = new Map<string, string>();
  for (let i = 0; i < catNames.length; i++) {
    const name = catNames[i]!;
    const slug = slugify(name);
    const cat = await prisma.galleryCategory.upsert({
      where: { slug },
      update: { name, order: i + 1 },
      create: { slug, name, order: i + 1 },
    });
    cats.set(name, cat.id);
  }
  for (let i = 0; i < GALLERY_ITEMS.length; i++) {
    const it = GALLERY_ITEMS[i]!;
    const id = `demo-gallery-${i + 1}`;
    const url = pickGalleryImage(i + 1);
    await prisma.galleryItem.upsert({
      where: { id },
      update: {
        title: it.title,
        imageUrl: url,
        thumbnailUrl: url,
        isPublished: true,
        categoryId: cats.get(it.category)!,
        order: i + 1,
      },
      create: {
        id,
        categoryId: cats.get(it.category)!,
        title: it.title,
        type: 'image',
        imageUrl: url,
        thumbnailUrl: url,
        order: i + 1,
        isPublished: true,
      },
    });
  }
}

async function seedPpdb(yearId: string): Promise<void> {
  const samples = [
    {
      fullName: 'Aji Permana Saputra',
      birthPlace: 'Jakarta',
      birthDate: new Date('2009-03-15'),
      fatherName: 'Bambang Saputra',
      motherName: 'Sri Astuti',
      status: 'submitted',
    },
    {
      fullName: 'Bunga Lestari Pertiwi',
      birthPlace: 'Bandung',
      birthDate: new Date('2009-07-21'),
      fatherName: 'Supriyanto',
      motherName: 'Nani Wahyuningsih',
      status: 'reviewed',
    },
    {
      fullName: 'Citra Dewi Maharani',
      birthPlace: 'Bogor',
      birthDate: new Date('2009-10-02'),
      fatherName: 'Hendra Wijaya',
      motherName: 'Ratna Kusuma',
      status: 'accepted',
    },
    {
      fullName: 'Dimas Anggoro Hartono',
      birthPlace: 'Tangerang',
      birthDate: new Date('2009-01-09'),
      fatherName: 'Rudi Hartono',
      motherName: 'Endah Mawarni',
      status: 'draft',
    },
    {
      fullName: 'Erika Putri Anggraini',
      birthPlace: 'Bekasi',
      birthDate: new Date('2009-12-30'),
      fatherName: 'Gunawan Wibowo',
      motherName: 'Yuliana Permata',
      status: 'rejected',
    },
    {
      fullName: 'Fajar Krisna Pratama',
      birthPlace: 'Depok',
      birthDate: new Date('2009-05-17'),
      fatherName: 'Joko Pratama',
      motherName: 'Mira Anggraini',
      status: 'submitted',
    },
  ];
  for (let i = 0; i < samples.length; i++) {
    const s = samples[i]!;
    const id = `demo-ppdb-${i + 1}`;
    await prisma.ppdbApplication.upsert({
      where: { id },
      update: { status: s.status, fullName: s.fullName },
      create: {
        id,
        academicYearId: yearId,
        status: s.status,
        fullName: s.fullName,
        birthPlace: s.birthPlace,
        birthDate: s.birthDate,
        nisn: `00${String(i + 12345678).slice(-8)}`,
        studentAddress: 'Jl. Pelajar No. 12 RT 03/04, Kelurahan Senayan',
        fatherName: s.fatherName,
        motherName: s.motherName,
        parentAddress: 'Jl. Pelajar No. 12 RT 03/04, Kelurahan Senayan',
        provinceId: '31',
        regencyId: '3171',
        districtId: '317101',
        villageId: '31710101',
        postalCode: '12190',
        contactEmail: `${slugify(s.fullName)}@gmail.com`,
        contactPhone: `+62-812-${String(1000 + i)}-${String(2000 + i)}`,
        submittedAt: s.status === 'draft' ? null : new Date(),
        reviewedAt: ['reviewed', 'accepted', 'rejected'].includes(s.status) ? new Date() : null,
        reviewerNotes:
          s.status === 'rejected'
            ? 'Berkas tidak lengkap'
            : s.status === 'accepted'
              ? 'Diterima jalur prestasi'
              : null,
      },
    });
  }
}

async function main(): Promise<void> {
  console.log('· Demo seed: roles');
  const roles = await ensureRoles();
  console.log('· Demo seed: school profile');
  await ensureSchoolProfile();
  console.log('· Demo seed: academic year');
  const year = await ensureAcademicYear();
  console.log('· Demo seed: subjects');
  const subjects = await seedSubjects();
  console.log('· Demo seed: 18 teachers + 6 wali kelas');
  const teachers = await seedTeachers(roles);
  console.log('· Demo seed: 6 classes');
  const classes = await seedClasses(year.id, teachers);
  console.log('· Demo seed: 120 students');
  const students = await seedStudents(roles, classes);
  console.log('· Demo seed: schedules');
  await seedSchedules(classes, subjects, teachers);
  console.log('· Demo seed: 14 days × 120 students attendance');
  await seedAttendance(students);
  console.log('· Demo seed: 5 CBT exams + soal');
  await seedExams(year.id, subjects, classes);
  console.log(`· Demo seed: ${NEWS_TITLES.length} berita`);
  await seedNews();
  console.log(`· Demo seed: ${GALLERY_ITEMS.length} item galeri`);
  await seedGallery();
  console.log('· Demo seed: pengumuman');
  await seedAnnouncements();
  console.log('· Demo seed: 6 PPDB applications');
  await seedPpdb(year.id);
  console.log('Demo seed complete.');
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
